version: '3.3'
services:
  chat-room-ws:
    restart: always
    env_file: 
      - ./.env
    build:
      context: ./
    networks:
      - chat-room-service
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/chat-room-ws/src
      - ./config:/app/chat-room-ws/config
      - ./scripts:/app/chat-room-ws/scripts
      - /app/chat-room-ws/.tmp
      - ./.tmp/node_modules:/app/chat-room-ws/node_modules
      - ${PWD}/package.json:/app/chat-room-ws/package.json
      - ${PWD}/package-lock.json:/app/chat-room-ws/package-lock.json
    links:
      - mysql
    environment:
      - RUNNING_ENV=docker
    
  mysql:
    image: mysql:latest
    networks:
      - chat-room-service
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_INIT_USER}
      MYSQL_PASSWORD: ${MYSQL_INIT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_INIT_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/var/lib/mysql

networks:
  chat-room-service:
